### ISSUE TITLE
Fails under node 5 on docker 

### ISSUE THREAD

**Issue by robbyoconnor** [node4good/formage#133]
```
node@92d5e926fc52:~/app$ npm start 
npm info it worked if it ends with ok
npm info using npm@3.7.5
npm info using node@v4.3.2
npm info lifecycle openmrsid@2.1.0~prestart: openmrsid@2.1.0
npm info lifecycle openmrsid@2.1.0~start: openmrsid@2.1.0

> openmrsid@2.1.0 start /home/node/app
> node app/app

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
[2016-03-28 05:48:47.168] [INFO] console - Running in development mode
/home/node/app/node_modules/formage/lib/registry.js:113
    if (!modelConfig.is_single) addDefaultModelActions(modelName, modelConfig, _.pluck(this.models, 'model'));
                                                                                 ^

TypeError: _.pluck is not a function
    at ModelRegistry.registerModel (/home/node/app/node_modules/formage/lib/registry.js:113:82)
    at ModelRegistry.<anonymous> (/home/node/app/node_modules/formage/lib/registry.js:30:14)
    at /home/node/app/node_modules/formage/node_modules/lodash-contrib/node_modules/lodash/lodash.js:4040:15
    at baseForOwn (/home/node/app/node_modules/formage/node_modules/lodash-contrib/node_modules/lodash/lodash.js:2573:24)
    at /home/node/app/node_modules/formage/node_modules/lodash-contrib/node_modules/lodash/lodash.js:4009:18
    at Function.forEach (/home/node/app/node_modules/formage/node_modules/lodash-contrib/node_modules/lodash/lodash.js:7634:11)
    at new ModelRegistry (/home/node/app/node_modules/formage/lib/registry.js:29:7)
    at Object.exports.init (/home/node/app/node_modules/formage/lib/Formage.js:77:38)
    at module.exports (/home/node/app/app/db-admin/index.js:13:24)
    at Object.<anonymous> (/home/node/app/app/app.js:168:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
```

**Comment by robbyoconnor** [comment]
FYI the problem is that you don't pin yoiur versions. When you don't pin dependencies...and non-backward compatible changes happen -- such as with lodash -- well..let...I fixed this on my own by pinning it -- but you should go through and actually do this -- it's really freaking bad.

**Comment by alonronin** [comment]
send a pull request, i'll merge it

2016-03-29 11:35 GMT+03:00 robbyoconnor <notifications@github.com>:

> FYI the problem is that you don't pin yoiur versions. When you don't pin
> dependencies...and non-backward compatible changes happen -- such as with
> lodash -- well..let...I fixed this on my own by pinning it -- but you
> should go through and actually do this -- it's really freaking bad.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/node4good/formage/issues/133#issuecomment-202777725>
>



-- 
Alon Valadji
Haroee 58, Ramat Gan, 52401
972-52-6-480-480
www.ronin.co.il

**Comment by robbyoconnor** [comment]
See #134

**Comment by robbyoconnor** [comment]
I'm not interested in trying to figure out what versions you coded against initially -- I was interested in getting it running for my use-case

**Comment by robbyoconnor** [comment]
@alonronin :point_up:

**Comment by refack** [comment]
Fixed.
